sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t baaboo2u/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true baaboo2u/docker-react npm run test -- --coverage