sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t baaboo2u/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true baaboo2u/docker-react npm run test -- --coverage

#http://dockerreact-env.eba-m7qipzib.us-east-2.elasticbeanstalk.com/
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-144745299261"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
